# Generated by Django 5.2.5 on 2025-08-22 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0039_alter_teaminvite_token"),
        ("mail", "0013_mailtemplate_role"),
        ("submission", "0082_question_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("base_url", models.URLField()),
                ("rest_auth_token", models.CharField()),
                ("queue", models.CharField()),
                ("initial_status", models.CharField(default="resolved")),
                ("custom_field_id", models.CharField(default="Pretalx ID")),
                ("custom_field_state", models.CharField(default="Pretalx State")),
                ("is_mail_html", models.BooleanField(default=True)),
                ("sync_interval", models.IntegerField(default=30)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rt_settings",
                        to="event.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("rt_id", models.PositiveIntegerField()),
                ("subject", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=64)),
                ("queue", models.CharField(max_length=200)),
                ("sync_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rt_tickets",
                        to="event.event",
                    ),
                ),
                (
                    "mails",
                    models.ManyToManyField(
                        related_name="rt_tickets", to="mail.queuedmail"
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rt_ticket",
                        to="submission.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("rest_auth_token", models.CharField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rt_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
